### PR TITLE
Some ItemImport clean up

### PR DESCRIPTION
**Pull request by kstamatis**
Hi @peterdietz,

I have done some cleanup in ItemImport class which is actually the merging of two almost similar methods that handle UI requests for batch import.

Apart from that, I have done some other changes regarding the unzip of files:

1) I pass as an argument in the zip method the path that files should be extracted. I keep backward compatibility by declaring the old method again and passing null to the new parameter.

2) I close the unzip file at the end of the unzip method, since I noticed that I could not delete the batci import folder at the end or at user request from the UI.

Regards,

Kostas

### CODE REVIEW

**Comment by peterdietz** [comment]
Hi Kostas,

Thanks, this looks good. I had wanted to do something similar, since there ended up being mostly duplicated methods. And this cleans that up.

I would merge it here, but the best way to get into DSpace/DSpace, would be to make a PR to that one.

**Comment by kstamatis** [comment]
Hi Peter,

there are some other (I think two) commits in your branch that are necessary for my commit in which you make some cleaning as well. That's why I PR-ed in this branch so as finally you PR to DSpace.

Isn't that true?

**Comment by peterdietz** [comment]
Ok, thanks. You are correct, I started that cleanup branch with 2 commits, 16 days ago. So yes, I'll review this, see if there is other code to clean up, and then PR as a code cleanup.

**Comment by peterdietz** [comment]
Sorry, was too slow to get this in before DSpace 5 RC1. Will try for between RC1 and RC2

**Pull request merged**
